In [10]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
print(arr1.shape)


(5,)


In [11]:
arr1 = np.array([1,2,3,4,5], dtype=np.float)
print(arr1.dtype)

float64


C:\Users\dns\AppData\Local\Temp/ipykernel_7904/1932073730.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr1 = np.array([1,2,3,4,5], dtype=np.float)


In [12]:
arr2 = np.arange(10,20)
print(arr2)

[10 11 12 13 14 15 16 17 18 19]


In [13]:
arr3 = np.arange(0,10,1.5)
print(arr3)

[0.  1.5 3.  4.5 6.  7.5 9. ]


In [14]:
arr_random = np.random.random((10,))
print(arr_random)

[0.72980993 0.9175413  0.25689552 0.50744543 0.31887115 0.42444027
 0.00542492 0.09547876 0.36498427 0.91575832]


In [15]:
arr2_sqrt=np.sqrt(arr2)
print(arr2_sqrt)

[3.16227766 3.31662479 3.46410162 3.60555128 3.74165739 3.87298335
 4.         4.12310563 4.24264069 4.35889894]


In [16]:
arr2_sin = np.sin(arr2)
print(arr2_sin)

[-0.54402111 -0.99999021 -0.53657292  0.42016704  0.99060736  0.65028784
 -0.28790332 -0.96139749 -0.75098725  0.14987721]


In [17]:
arr4 = np.arange(10,20)

In [18]:
print(arr4+arr2)

[20 22 24 26 28 30 32 34 36 38]


In [19]:
print(arr4*arr2)

[100 121 144 169 196 225 256 289 324 361]


In [20]:
print(arr4**3)

[1000 1331 1728 2197 2744 3375 4096 4913 5832 6859]


In [21]:
print(arr4.max())

19


In [22]:
print(arr4.mean())

14.5


In [23]:
print(arr4.sum())

145


In [24]:
print(arr4.std())

2.8722813232690143


In [25]:
print(arr4 > 14)

[False False False False False  True  True  True  True  True]


In [26]:
print(arr4.ndim)

1


In [27]:
print(np.insert(arr4, 5, 4))

[10 11 12 13 14  4 15 16 17 18 19]


In [28]:
print(np.delete(arr4, 4))

[10 11 12 13 15 16 17 18 19]


In [29]:
print(np.sort(arr4))

[10 11 12 13 14 15 16 17 18 19]


In [31]:
arr5 = np.concatenate((arr1,arr2))
print(arr5)

[ 1.  2.  3.  4.  5. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]


In [32]:
print(arr5[(arr5 < 5)])

[1. 2. 3. 4.]


In [33]:
print(arr5[(arr5 < 10) & (arr5 > 5)])

[]


In [34]:
print(arr5[(arr5 < 3) & (arr5 > 170)])

[]
