In [71]:
import numpy as np

In [66]:
matrix1 = np.array([(1,2,3),(4,5,6),(7,8,9)])

In [67]:
matrix1.shape

(3, 3)

In [68]:
print(matrix1.ndim)

2


In [69]:
print(matrix1.size)

9


In [70]:
print(matrix1.reshape(1,9))

[[1 2 3 4 5 6 7 8 9]]


In [53]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [54]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [55]:
print(np.full((3,3),5))

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [56]:
print(np.empty((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [57]:
print(np.empty(2))

[-1.05553488e-018  9.11530889e+122]


In [58]:
matrix2 = np.array([(10,11,12),(13,14,15),(16,17,18)])

In [59]:
print(matrix1+matrix2)

[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [60]:
print(np.delete(matrix1, 1, axis=0))


[[1 2 3]
 [7 8 9]]


In [61]:
print(np.mean(matrix1, axis=0))

[4. 5. 6.]


In [62]:
print(matrix2[1,2])
print(matrix2[: , 1])
print(matrix2[matrix2 > 10])
print(matrix1 < 5)

15
[11 14 17]
[11 12 13 14 15 16 17 18]
[[ True  True  True]
 [ True False False]
 [False False False]]


In [63]:
matrix3 = np.array([(1,4,7),(3,8,5),(9,2,6),(11,0,22)])
print(matrix3[:,1])
print(matrix3[2,:])

[4 8 2 0]
[9 2 6]


In [64]:
matrix4 = np.array([(67,4,23),(44,12,7),(88,6,0),(65,2,17)])
print(np.append(matrix4,np.array([1,2,3])))
print(matrix4[matrix4 > 5])

[67  4 23 44 12  7 88  6  0 65  2 17  1  2  3]
[67 23 44 12  7 88  6 65 17]
