In [1]:
import numpy as np

In [2]:
from random import randint

In [3]:
matrix1 = np.empty((12,12), int)

In [6]:
matrix2 = np.empty((12,12), int)

In [7]:
for i in range(0, 12):
    for j in range(0,12):
        matrix1[i][j] = randint(0,100)
        matrix2[i][j] = randint(0,100)

In [8]:
print(matrix1)

[[ 63  84  44  20  55  76  13  33  41   3  33  59]
 [ 17  61  94 100  45  22   1  83  20  93  68   3]
 [ 40  45  92  36  12   4  39  49  78  68  62  65]
 [ 13  28  32   0  97  12  26  40  86  29  11  64]
 [ 91  66  98  96  67  13  39  81   2  85   4  18]
 [ 57  79  27  88  78  11  48  12  79  99  65  94]
 [ 87  53  63  43  67  33  90  18  83  51  14  15]
 [ 50  98  21  61  75  63  62  32  67  60  88  99]
 [  3  45  50  92  27   3  92  38  19  53  97  36]
 [ 73  38  72  63  54  29   1  29  81  19  92  72]
 [  4  12  55  52  29  71  33  32  27  12  16  96]
 [ 10  95  84   5  56  75  58  20  68  77  73  52]]


In [9]:
optional_row = matrix1[1]

In [10]:
optional_col = matrix1[:, 4]

In [11]:
print(optional_row)

[ 17  61  94 100  45  22   1  83  20  93  68   3]


In [12]:
print(optional_col)

[55 45 12 97 67 78 67 75 27 54 29 56]


In [13]:
print(matrix1[matrix1 > 5])

[ 63  84  44  20  55  76  13  33  41  33  59  17  61  94 100  45  22  83
  20  93  68  40  45  92  36  12  39  49  78  68  62  65  13  28  32  97
  12  26  40  86  29  11  64  91  66  98  96  67  13  39  81  85  18  57
  79  27  88  78  11  48  12  79  99  65  94  87  53  63  43  67  33  90
  18  83  51  14  15  50  98  21  61  75  63  62  32  67  60  88  99  45
  50  92  27  92  38  19  53  97  36  73  38  72  63  54  29  29  81  19
  92  72  12  55  52  29  71  33  32  27  12  16  96  10  95  84  56  75
  58  20  68  77  73  52]
